services:
  mongo-api:
    image: reshma0209/mongo-api:8
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}

  mysql-api:
    image: reshma0209/mysql-api:8
    ports:
      - "8080:6000"

  frontend:
    image: reshma0209/frontend:8
    ports:
      - "80:80"
